### ISSUE TITLE
Video clip instead of snapshot

### ISSUE THREAD

**Issue by looxonline** [brutella/hkcam#35] opened 2019-06-21 07:31 UTC
Would it be possible to capture a short clip instead of a still snapshot when motion is detected?

**Comment by brutella** [comment] 2019-06-21 08:20
This feature is planned.

Duplicate of #33

**Closed by brutella** 2019-06-21 08:20 UTC

**Comment by looxonline** [comment] 2019-06-21 09:20
If I understand correctly the secure video implementation requires a subscription to at least the 200GB iCloud service and then it offers a rolling recording in the cloud of 10 days and timestamps events within that recording.

What I am talking about is different. Instead of storing the video in iCloud it could still be stored on the local device (like the snapshots are) so that no monthly sub is required and they would only be captured and stored based on an event and not on a full rolling 10 day window.
