### ISSUE TITLE
Camera resolution

### ISSUE THREAD

**Issue by AndreaCCIE** [brutella/hkcam#30] opened 2019-06-12 16:09 UTC
I've got a Raspberry Camera 2.1 (8 MP), but the video quality is very low and everything is pixelated.
It looks like the streaming is set to 1024x768, and the real fps is 5:

2019-06-12_16:06:30.32669     Stream #0:0: Video: h264 (h264_omx), yuv420p, **1024x768**, q=2-31, 299 kb/s, 30 fps, 90k tbn, 30 tbc

frame=   36 **fps=3.7** q=-1.0 size=N/A time=00:00:09.37 bitrate=N/A speed=0.977x     speed=0.956x    .994x

Any way to tune this?

<img width="1077" alt="Screenshot 2019-06-12 at 17 03 16" src="https://user-images.githubusercontent.com/48698293/59367804-c554de00-8d34-11e9-9ae1-18da8b8f3476.png">

**Comment by brutella** [comment] 2019-06-12 20:27
I'm currently working on a fix.

**Comment by AchimPieters** [comment] 2019-06-13 14:36
See issue `Picture quality pi zero #4`

**Comment by AndreaCCIE** [comment] 2019-06-13 14:41
Saw that, but this is not an HomeKit "limitation" because other cameras can get to 1080p without any problem, so there should be a workaround.

**Comment by fisch55** [comment] 2019-06-21 13:02
Same here.... video quality not so good. 😢

**Comment by brutella** [comment] 2019-06-21 13:15
Duplicate of #4

**Closed by brutella** 2019-06-21 13:15 UTC
