### ISSUE TITLE
Is any support for this project? Or its as is....

### ISSUE THREAD

**Issue by alexsalex** [brutella/hkcam#83] opened 2020-06-11 06:28 UTC
Subj

**Comment by brutella** [comment] 2020-06-11 07:18
What issue do you have?

**Comment by alexsalex** [comment] 2020-06-16 01:09
https://github.com/brutella/hkcam/issues/82
https://github.com/brutella/hkcam/issues/81

Please

**Comment by alexsalex** [comment] 2020-06-22 20:34
any updates?

**Comment by brutella** [comment] 2020-07-06 08:43
I've replied to #81 and #82 is a duplicate of #45

**Closed by brutella** 2020-07-06 08:43 UTC
